# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJKVqkLzUBoQ68-3y75RSYLVY9dYhQEo

Cy mitchell

03/24/2024

Legal and ethical issues with web scraping include potential violations of terms of service, copyright infringement, data privacy concerns, and the possibility of disrupting the target website's functionality or performance.
A trend line in data visualization is a line that shows the general direction of a dataset's movement over time or other ordered categories. It indicates the overall trend or pattern within the data, helping to identify whether values are increasing, decreasing, or remaining stable.

Problem 1
"""

import urllib.request
import re

url = "https://en.wikipedia.org/wiki/Web_scraping"

with urllib.request.urlopen(url) as response:
    html_content = response.read().decode('utf-8')

url_pattern = re.compile(r'href="(https?://.*?)"')

links = re.findall(url_pattern, html_content)

link_list = []
for link in links:
    link_list.append(link)

print("Number of links found:", len(link_list))

for link in link_list:
    print(link)

"""Problem 2"""

import matplotlib.pyplot as plt
import numpy as np

list1 = [2,2,3,3,7,15,15,21,21,21,22,22,24,30,33,38,39,42,47,49,51,51,52,53,55,58,59,60,60,61]

list2 = [-19.26,12.19,9.29,-9.51,14.80,11.23,3.63,-1.08,16.16,3.45,-2.77,7.46,7.38,15.66,14.73,31.00,26.48,19.28,14.42,36.38,33.35,52.06,28.63,42.91,32.10,29.85,14.40,37.21,21.56,25.36]

plt.figure(figsize=(10, 5))
plt.plot(list1, label='List 1')
plt.plot(list2, label='List 2')
plt.xlabel('Index')
plt.ylabel('Values')
plt.title('Line Graph of List 1 and List 2')
plt.legend()
plt.show()

plt.figure(figsize=(10, 5))
plt.scatter(range(len(list1)), list1, label='List 1')
plt.scatter(range(len(list2)), list2, label='List 2')
plt.xlabel('Index')
plt.ylabel('Values')
plt.title('Scatter Plot of List 1 and List 2')
plt.legend()
plt.show()

plt.figure(figsize=(10, 5))
plt.scatter(range(len(list1)), list1, label='List 1')
plt.scatter(range(len(list2)), list2, label='List 2')

z = np.polyfit(range(len(list2)), list2, 1)
p = np.poly1d(z)
plt.plot(range(len(list2)), p(range(len(list2))), "r--", label="Trend Line (List 2)")

plt.xlabel('Index')
plt.ylabel('Values')
plt.title('Scatter Plot of List 1 and List 2 with Trend Line')
plt.legend()
plt.show()

"""Problem 3"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'TeamName': ['Reese', 'Barnes', 'Jones', 'Javez', 'Smith', 'Heath', 'Jacks', 'Weeks', 'Mitch', 'Rankle'],
    'HighestScore': [112, 103, 127, 99, 130, 107, 89, 120, 122, 90],
    'LowestScore': [47, 87, 70, 51, 100, 101, 38, 97, 110, 55]
}

df = pd.DataFrame(data)

plt.figure(figsize=(10, 5))
sns.lineplot(data=df[['HighestScore', 'LowestScore']], dashes=False)
plt.xlabel('Team')
plt.ylabel('Score')
plt.title('Highest and Lowest Scores of Teams')
plt.xticks(ticks=range(len(df['TeamName'])), labels=df['TeamName'])
plt.grid(True)
plt.show()