# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aO7BKK-YUP1L_gRsTK_qU5f-B_z13q7H
"""

print("CY Mitchell" + "\n" + "01/30/2024" + "\n" + "A data structure in programming is a way of organizing and storing data to perform operations efficiently. It defines the relationships and functions that can be applied to the data, allowing for easy retrieval, modification, and manipulation." + "\n" + "Mutable data structures can be changed after creation, while immutable ones cannot be modified once created. In Python, lists are mutable, meaning you can add, remove, or modify elements, while tuples are immutable, and their elements cannot be changed once the tuple is created." )

my_list = [1, 2, 3, 4, 5]

print("Full List:", my_list)

print("Third Element:", my_list[2])

print("Length of List:", len(my_list))

sum_first_and_third = my_list[0] + my_list[2]
print("Sum of First and Third:", sum_first_and_third)

word_list = ['nike', 'adidas', 'Puma', 'converse', 'apple', '', 'microsoft', 'pepsi', 'pasta', 'tacos']